name: Vérification PEP 8

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-pep8:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Installer flake8
        run: pip install flake8
      
      - name: Vérifier PEP 8 avec flake8
        run: flake8 src/ --max-line-length=88 --statistics